name       : xorg-driver-video-vmware
version    : 13.3.0
release    : 16
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-vmware-13.3.0.tar.gz : 3a29f105b331523e532542bf75d716526877ec6d5ba07b079ed245b02bd4d084
license    :
    - MIT
summary    : VMWare Video Driver
component  : xorg.driver
description: |
    The Xorg VMware Driver package contains the X.Org Video Driver for VMware SVGA virtual video cards.
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
