name       : xorg-driver-video-vmware
version    : 13.3.0
release    : 25
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-vmware-13.3.0.tar.gz : 3a29f105b331523e532542bf75d716526877ec6d5ba07b079ed245b02bd4d084
license    : MIT
summary    : VMWare Video Driver
component  : xorg.driver
description: |
    The Xorg VMware Driver package contains the X.Org Video Driver for VMware SVGA virtual video cards.
optimize   :
    - no-bind-now
    - no-symbolic
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(pciaccess)
    - pkgconfig(xatracker)
    - pkgconfig(xext)
    - pkgconfig(xorg-server)
    - pkgconfig(xproto)
setup      : |
    %patch -p0 < $pkgfiles/gcc8.diff
    %patch -p1 < $pkgfiles/headers-include-priority.patch
    %configure
build      : |
    %make
install    : |
    %make_install
