name        : xorg-driver-video-vmware
version     : 13.1.0
release     : 7
source      :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-video-vmware-13.1.0.tar.bz2 : 3c1d244e4b1b77e92126957965cdc9fb82de4c215c0706a3a8aaff6939e4a0cc
license     :
    - MIT
summary     : VMWare Video Driver
component   : xorg.driver
builddeps   :
    - pkgconfig(xorg-server)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   : no-bind-now
description : |
    The Xorg VMware Driver package contains the X.Org Video Driver for VMware SVGA virtual video cards.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
