name       : xorg-driver-video-vmware
version    : 13.2.1
release    : 15
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-vmware-13.2.1.tar.gz : 71908666e2743651accd58823ed4b201a078864203cf49b634cedca3e616abc1
license    :
    - MIT
summary    : VMWare Video Driver
component  : xorg.driver
description: |
    The Xorg VMware Driver package contains the X.Org Video Driver for VMware SVGA virtual video cards.
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
